[package]
authors = [
  "Sean Bowe <ewillbefull@gmail.com>",
  "Jack Grigg <jack@z.cash>",
]
license = "MIT/Apache-2.0"
name = "group"
readme = "README.md"
version = "0.13.0"

description = "Elliptic curve group traits and utilities"
documentation = "https://docs.rs/group/"
edition = "2021"
homepage = "https://github.com/zkcrypto/group"
repository = "https://github.com/zkcrypto/group"

[dependencies]
ff = { version = "0.13", default-features = false }
# ff = {path = "../ff"}
rand = {version = "0.8", optional = true, default-features = false}
rand_core = {version = "0.6", default-features = false}
rand_xorshift = {version = "0.3", optional = true}
subtle = {version = "2.2.1", default-features = false}

# Crate for exposing the dynamic memory usage of the w-NAF structs.
memuse = {version = "0.2", optional = true}

[features]
alloc = []
default = ["alloc", "tests"]
tests = ["alloc", "rand", "rand_xorshift"]
wnaf-memuse = ["alloc", "memuse"]

[badges]
maintenance = {status = "actively-developed"}
